version: "2"
services:
  sen2r:
    build: .
    volumes:
      - ./data:/app/data

  s2_monitor:
    build:
      dockerfile: Dockerfile.monitoring
      context: .
    volumes:
      - ./data:/app/data
    environment:
      - S2_USER
      - S2_PASS
      - S2_AOI
      - S2_OUTDIR
      - S2_CLOUDCOVERAGE
